import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ClerkProvider, SignInButton, SignUpButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end items-center p-4 gap-4 h-16 bg-gray-100 text-black">
            <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>

            <nav className="col-span-2 flex flex-col gap-y-8 px-4 py-8">
              <Link href={"/forces"}>Order of Battle</Link>
              {/* <Link href={"/login"}>Login</Link> */}
            </nav>
          </header>
          <section className="bg-gray-100 text-black grid grid-cols-12 gap-4 lg:gap-8 px-4 lg:px-8">
              <div className="col-span-12">
                <h1 className="text-4xl">Crusade Tracker</h1>
              </div>
              <div className="pt-8 col-span-12 min-h-screen">{children}</div>
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
