import { ClerkProvider, SignedIn, UserButton } from "@clerk/nextjs";
import { currentUser } from "@clerk/nextjs/server";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"]
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await currentUser();

  // Create user in DB
  if (user) {
    try {
      const addRes = await fetch(`${process.env.LOCALHOST}/api/users`, {
        method: "POST",
        headers: {
          "content-type": "application/json"
        },
        body: JSON.stringify({
          clerkID: user.id,
          forces: []
        })
      }).then((resp) => resp.json());

      console.log(addRes);
    } catch (error) {
      console.error(error);
    }
  }

  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <header className="flex justify-end bg-gray-100 p-4 text-black gap-4">
            <SignedIn>
              <p>Welcome, {user?.firstName}</p>
              <UserButton />
            </SignedIn>
          </header>
          <section className="bg-gray-100 text-black grid grid-cols-12 gap-4 lg:gap-8 px-4 lg:px-8">
            <div className="pt-8 col-span-12 min-h-screen">{children}</div>
          </section>
        </body>
      </html>
    </ClerkProvider>
  );
}
