import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-100 text-black min-h-screen grid grid-cols-12 gap-4 lg:gap-8">
          <nav className="col-span-2 flex flex-col gap-y-8 px-4 py-8">
            <Link href={"/create-force"}>Create force</Link>
            {/* <Link href={"/login"}>Login</Link> */}
          </nav>

          <section className="col-span-10 py-8 px-4">
            <h1 className="text-4xl">Crusade Tracker</h1>
            <div className="pt-8">{children}</div>
          </section>
        </div>
      </body>
    </html>
  );
}
